### ISSUE TITLE
AGOL Setup Tool  403 error

### ISSUE THREAD

**Issue by dkglasgow** [mpanunto/PanunTools#2]
I was trying to test out this tool. I have had no luck in running it. I keep getting the same error. I know that my user and password are correct. Any thoughts? here is the tool results text. Thanks in advanced!

Incident Setup AGOL
=====================
Parameters

NIFC ArcGIS Online Username     dglasgow_nifc
NIFC ArcGIS Online Password     xxxxx
Specify Incident Name (ex: Rush Creek)     TESTFIRE
Specify Unique Fire ID (ex: 2021-IDPAF-000422)     2022-CATST-001
Create Incident Specific AGOL Groups?     Yes
Create Archive Group     
Create Logistics Group     
Create Mobile Editing Group     true
Create Public Information Group     
Create Viewer Group     true
Create Working Group     true
Create Incident Specific Feature Services?     Yes
Create Photo Points Feature Service     true
Create Incident Specific Web Maps?     Yes
Create Incident Web Map     true
Create View Only Incident Web Map     true
Create Suppression Repair Web Map     true
Create SITL Approver Web Map     
=====================
Messages

Start Time: Sunday, July 17, 2022 10:57:55 PM
​
Incident Setup AGOL Tool developed by Matt Panunto, DOI-BLM
​
IMPORTING LIBRARIES
New version of PanunTools available (v20220715) at https://github.com/mpanunto/PanunTools
​
Traceback (most recent call last):
  File "C:\Users\Dustin\FireNet\2022_CAYNP_Washburn - GIS Data\2022_Washburn\tools\PanunTools-main\PanunTools.tbx#IncidentSetupAGOL_PanuntoolsAlias.py", line 123, in <module>
  File "C:\Users\Dustin\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\Lib\site-packages\arcgis\gis\__init__.py", line 5507, in get
    raise e
  File "C:\Users\Dustin\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\Lib\site-packages\arcgis\gis\__init__.py", line 5497, in get
    item = self._portal.get_item(itemid)
  File "C:\Users\Dustin\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\Lib\site-packages\arcgis\gis\_impl\_portalpy.py", line 1352, in get_item
    return self.con.post("content/items/" + itemid, self._postdata())
  File "C:\Users\Dustin\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\Lib\site-packages\arcgis\gis\_impl\_con\_connection.py", line 1079, in post
    force_bytes=kwargs.pop("force_bytes", False),
  File "C:\Users\Dustin\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\Lib\site-packages\arcgis\gis\_impl\_con\_connection.py", line 625, in _handle_response
    self._handle_json_error(data["error"], errorcode)
  File "C:\Users\Dustin\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-1\Lib\site-packages\arcgis\gis\_impl\_con\_connection.py", line 648, in _handle_json_error
    raise Exception(errormessage)
Exception: You do not have permissions to access this resource or perform this operation.
(Error Code: 403)

Failed script Incident Setup AGOL...
Failed to execute (IncidentSetupAGOL).
Failed at Sunday, July 17, 2022 10:58:00 PM (Elapsed Time: 4.70 seconds)

**Comment by mpanunto** [comment]
I think I fixed it. I had a line of code referencing a Northern Rockies web map that is not shared Org-wide. Try downloading the latest version and give it another shot.

**Comment by dkglasgow** [comment]
Worked Like a charm now!. I can't thank you enough for these tools. very time saving. Thanks!
